export * from '@dentist/components/landing/hero';
export * from '@dentist/components/landing/about-us';
export * from '@dentist/components/landing/banners';
export * from '@dentist/components/landing/dentits-map';
export * from '@dentist/components/landing/footer';
export * from '@dentist/components/landing/nav-bar';
export * from '@dentist/components/landing/pricings';
export * from '@dentist/components/landing/steps-section';
export * from '@dentist/components/landing/services';